# Search
search: 
  enable: true
  service: hexo # google/hexo/algolia/azure/baidu
  # google 
  google_api_key:
  google_engine_id:
  # algolia
  algolia_app_id:
  algolia_api_key:
  algolia_index_name:
  # azure
  azure_service_name:
  azure_index_name:
  azure_query_key:
  # baidu
  baidu_api_id:


# navigation menu
menu:
  
  - name: 微服务
    slug: microservices
    url: /categories/Microservice
  - name: 服务网格
    slug: service-mesh
    url: /categories/Service-Mesh
  - name: 分布式事务
    slug: distrubited-transaction
    url: /categories/distrubited-transaction
  - name: 分布式系统
    slug: distrubited-system
    url: /categories/distrubited-system
  - name: Java
    slug: java
    url: /categories/java
  - name: Go
    slug: go
    url: /categories/go
  - name: 归档
    slug: archives
    url: /archives
  - name: About
    slug: about
    url: /about
 
# friends link
links:
  - name: ClassicOldSong
    url: https://ccoooss.com
  - name: Frantic1048
    url: https://frantic1048.logdown.com/
  - name: Hclmaster
    url: https://hclmaster.github.io/
  - name: WANG Hsü-Tung
    url: https://whst.github.io/

# widgets
widgets:
  - about
  - categories
  - tagcloud
  - links  

# Less
less:
  compress: true

# use url, not username
social:
- slug: github
  url: https://github.com/stkevintan
- slug: twitter
  url: https://twitter.com/kevinsfork
- slug: rss
	url: /atom.xml
